const categories = [
    {id: 3001, categLabel: "Tops", categGroup: "Women", imgFile: "crop-top.png"},
    {id: 3002, categLabel: "Bottoms", categGroup: "Women", imgFile: "skirt.png"},
    {id: 3003, categLabel: "Dresses", categGroup: "Women", imgFile: "dress.png"},
    {id: 3004, categLabel: "Bags", categGroup: "Women", imgFile: "fbags.png"},
    {id: 3005, categLabel: "Shoes", categGroup: "Women", imgFile: "fshoes.png"},
    {id: 3006, categLabel: "Accessories", categGroup: "Women", imgFile: "jewelry.png"},
    {id: 3007, categLabel: "Tops", categGroup: "Men", imgFile: "shirt.png"},
    {id: 3008, categLabel: "Bottoms", categGroup: "Men", imgFile: "shorts.png"},
    {id: 3009, categLabel: "Formal Wear", categGroup: "Men", imgFile: "suit.png"},
    {id: 3010, categLabel: "Bags", categGroup: "Men", imgFile: "mbag.png"},
    {id: 3011, categLabel: "Shoes", categGroup: "Men", imgFile: "mshoes.png"},
    {id: 3012, categLabel: "Accessories", categGroup: "Men", imgFile: "watch.png"},
    {id: 3013, categLabel: "Tops", categGroup: "Kid", imgFile: "ktops.png"},
    {id: 3014, categLabel: "Bottoms", categGroup: "Kid", imgFile: "kpants.png"},
    {id: 3015, categLabel: "Bags", categGroup: "Kid", imgFile: "kbags.png"},
    {id: 3016, categLabel: "Shoes", categGroup: "Kid", imgFile: "kshoes.png"},
    {id: 3017, categLabel: "Baby Products", categGroup: "Kid", imgFile: "bproducts.png"},
    {id: 3018, categLabel: "Toys", categGroup: "Kid", imgFile: "toys.png"},
    {id: 3019, categLabel: "Home Entertainment", categGroup: "Home", imgFile: "h-entertainment.png"},
    {id: 3020, categLabel: "Home & Living", categGroup: "Home", imgFile: "h-entertainment.png"},
    {id: 3021, categLabel: "Electronics", categGroup: "Home", imgFile: "h-oven.png"},
    {id: 3022, categLabel: "Furniture", categGroup: "Home", imgFile: "h-chair.png"},
    {id: 3023, categLabel: "Kitchenware", categGroup: "Home", imgFile: "h-kitchen.png"},
    {id: 3024, categLabel: "Outdoor & Garden", categGroup: "Home", imgFile: "h-garden.png"},
]

export default categories